name: yessine
description: "A personal portfolio"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.4
  cloud_firestore: ^4.17.5
  icons_plus: ^5.0.0
  url_strategy: ^0.2.0
  firebase_core: ^2.25.4
  lottie: ^3.0.0
  flutter_native_splash: ^2.3.10
  vertical_tab_bar_view: ^0.0.1
  cached_network_image: ^3.4.1
  date_format: ^2.0.9
  fluttertoast: ^8.2.8
  flutter_widget_from_html: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
